version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "media-labs-transcribe-stack"
s3_prefix = "media-labs-transcribe"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
